[build]
target = "riscv32im-unknown-none-elf"

[target.riscv32im-unknown-none-elf]
runner = """qemu-system-riscv32 \
-nographic -machine virt -m 3G \
-serial mon:stdio \
-drive file=elf,format=raw,id=elf,if=none,readonly=on -device virtio-blk-device,drive=elf,serial=CENO-GUEST-ELF \
-kernel"""
rustflags = [
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tlink.x",
]